server:
  port: 9000

spring:
  application:
    name: uaa

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    client:
      client-id: springDev1
      client-secret: test
      authorized-grant-types: password.client_credentials,authorization_code,refresh_token
      scope: read,write