server:
  port: ${PORT:9999}

spring:
  application:
    name: authorization-server

security:
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret