server:
  port: 9000
  context-path: /uaa

logging:
  level:
    org.springframework.security: DEBUG

security:
#  user:
                ##    name: admin
                ##    password: admin
                ##    role: ADMIN
  oauth2:
    client:
      client-id: springDev1
      client-secret: test
      authorized-grant-types: password.client_credentials,authorization_code,refresh_token
      scope: read,write