server:
  port: 9999
  use-forward-headers: true

spring:
  application:
    name: gateway-server

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"
  routes:
    uaa:
      path: /uaa/**
      service-id: uaa
      sensitiveHeaders:
      strip-prefix: false
    routes:
      path: /routes/**
      service-id: routes
      sensitiveHeaders:
      strip-prefix: false

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

