server:
  port: 8080

spring:
  application:
    name: gateway-server

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"
  routes:
    uaa:
      path: /uaa/**
      service-id: uaa
    routes:
      path: /routes/**
      service-id: routes

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url.defaultZone: http://localhost:8761/eureka/

