server:
  port: 2222

spring:
  application:
    name: routes

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/